name: Nanika Plugin
version: @version@
main: com.github.kumitatepazuru.nanikaplugin.NanikaPlugin
api-version: 1.16
authors: [ kumitatepazuru ]
description: なにかサーバー専用プラグイン
website: https://github.com/kumitatepazuru/nanika_plugin/
